const express = require("express"); //attach express module 
const bodyParser = require("body-parser"); // add body-parser module
const ejs = require("ejs"); // add ejs module

const homeStartingContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat. Condimentum mattis pellentesque id nibh tortor id. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Scelerisque in dictum non consectetur a erat. Volutpat sed cras ornare arcu dui vivamus arcu. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Viverra justo nec ultrices dui. Non blandit massa enim nec dui nunc mattis enim. Ullamcorper sit amet risus nullam eget felis.Est lorem ipsum dolor sit amet consectetur adipiscing. Enim sit amet venenatis urna. Libero nunc consequat interdum varius sit amet mattis vulputate. Mauris pharetra et ultrices neque. Egestas purus viverra accumsan in nisl. Enim nec dui nunc mattis. Amet cursus sit amet dictum sit amet justo donec. Placerat in egestas erat imperdiet sed euismod. Amet porttitor eget dolor morbi. Vitae tortor condimentum lacinia quis. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Fames ac turpis egestas sed.Aliquam nulla facilisi cras fermentum. Ac tortor dignissim convallis aenean et tortor at. Consectetur a erat nam at. Pellentesque elit ullamcorper dignissim cras. Quam lacus suspendisse faucibus interdum posuere. Nibh sed pulvinar proin gravida hendrerit lectus. Pharetra sit amet aliquam id diam maecenas. Diam maecenas sed enim ut sem viverra. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Quam adipiscing vitae proin sagittis nisl rhoncus. Porttitor eget dolor morbi non. In hac habitasse platea dictumst vestibulum rhoncus. Nisl purus in mollis nunc sed. Fusce ut placerat orci nulla. Orci a scelerisque purus semper eget duis at tellus at. Suspendisse in est ante in nibh mauris cursus mattis. At lectus urna duis convallis convallis tellus. Eu non diam phasellus vestibulum lorem. Congue nisi vitae suscipit tellus. Bibendum ut tristique et egestas quis ipsum suspendisse. Nisl suscipit adipiscing bibendum est. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Vulputate eu scelerisque felis imperdiet. Auctor eu augue ut lectus. Nec ultrices dui sapien eget mi proin. Risus feugiat in ante metus dictum at. Donec pretium vulputate sapien nec. Ac tortor dignissim convallis aenean et. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Sit amet mattis vulputate enim.";
const aboutContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque aliquam vestibulum morbi blandit cursus risus. Eu feugiat pretium nibh ipsum consequat nisl vel. Nascetur ridiculus mus mauris vitae. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Vivamus arcu felis bibendum ut tristique et. Nibh tellus molestie nunc non blandit massa. Metus aliquam eleifend mi in nulla posuere sollicitudin. Urna et pharetra pharetra massa massa. Fusce id velit ut tortor pretium viverra suspendisse. Augue lacus viverra vitae congue. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Ipsum dolor sit amet consectetur adipiscing. Malesuada fames ac turpis egestas maecenas pharetra convallis. Laoreet sit amet cursus sit amet. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Arcu non odio euismod lacinia. Aliquet enim tortor at auctor urna nunc. Elementum curabitur vitae nunc sed. Diam maecenas ultricies mi eget mauris pharetra. Praesent semper feugiat nibh sed. Adipiscing enim eu turpis egestas pretium. Vel facilisis volutpat est velit. Risus pretium quam vulputate dignissim suspendisse in. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Proin fermentum leo vel orci porta non pulvinar neque. Etiam non quam lacus suspendisse faucibus interdum posuere. Fringilla est ullamcorper eget nulla facilisi etiam. Egestas purus viverra accumsan in nisl.";
const contactContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui. Blandit aliquam etiam erat velit scelerisque in dictum non. Aliquam nulla facilisi cras fermentum odio eu. Sit amet venenatis urna cursus. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Augue neque gravida in fermentum et sollicitudin. Blandit turpis cursus in hac habitasse. Sit amet volutpat consequat mauris nunc. Scelerisque viverra mauris in aliquam sem. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Pharetra convallis posuere morbi leo urna molestie at elementum. Convallis tellus id interdum velit laoreet. Pellentesque sit amet porttitor eget dolor morbi.";

const app = express(); // bind express module to app

app.set('view engine','ejs'); // set view engine to ejs

app.use(bodyParser.urlencoded({extended : true})); // written to use body-parser

app.use(express.static("public")); // use public folder to access some files

app.listen(3000,function() {
  console.log("Server is started at 3000");
});